FROM node:0.12.4-onbuild

EXPOSE  8080

# The address where prerender can access your application
# Using the Boot2Docker IP here. Change if you are running behind a proxy
ENV PUBLIC_HOST_ADDRESS 192.168.59.103:8080